{% set name = "libsemigroups_pybind11" %}
{% set version = "0.1.4" %}

package:
  name: libsemigroups_pybind11
  version: {{ version }}

source:
  url: https://github.com/libsemigroups/libsemigroups_pybind11/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a27ca74884c5a608b83c60586a3b308ea6bbe5c4a6b2c11ea77fb337bef1bf33

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libsemigroups
    - pkgconfig >=0.29.2
    - packaging >=20.4
    - pybind11 >=2.6
  run:
    - python
    - libsemigroups >=2.0.2
    - pybind11 >=2.6

test:
  imports:
    - libsemigroups_pybind11
  requires:
    - pytest=6.2.4
  source_files:
    - tests/
  commands:
    - pytest -vv tests/test_*.py

about:
  home: https://libsemigroups.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python package for using the C++ library libsemigroups via pybind11
  dev_url: https://github.com/libsemigroups/libsemigroups_pybind11

extra:
  recipe-maintainers:
    - chinmayanagpal
