{% set name = "libsemigroups_pybind11" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libsemigroups_pybind11-{{ version }}.tar.gz
  sha256: 56d191d791b92654e5193266e0a68dcc0ff62ff3e8b0fec13b4f9f9265317789

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
    - pkgconfig                           # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools >=64
    - setuptools-scm >=8
    - libsemigroups >=3.1.3
    - packaging
    - pip
    - pkgconfig
    - pybind11
    - python
  run:
    - numpy
    - python
    - python-graphviz
    - typing_extensions

test:
  imports:
    - libsemigroups_pybind11
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/

about:
  home: https://libsemigroups.github.io/libsemigroups_pybind11/
  dev_url: https://github.com/libsemigroups/libsemigroups_pybind11
  summary: A python package for the libsemigroups C++ library.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - james-d-mitchell
    - joseph-edwards
