{% set name = "libsemigroups_pybind11" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libsemigroups_pybind11-{{ version }}.tar.gz
  sha256: 3fc2dca669fe4468d524d293099df5dd84074b6049f88ce222ea560b36f5bdec

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools >=64
    - setuptools-scm >=8
    - libsemigroups >=3.1.3
    - packaging
    - pip
    - pkgconfig
    - pybind11
    - python
  run:
    - numpy
    - python
    - python-graphviz
    - typing_extensions

test:
  imports:
    - libsemigroups_pybind11
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/

about:
  home: https://libsemigroups.github.io/libsemigroups_pybind11/
  dev_url: https://github.com/libsemigroups/libsemigroups_pybind11
  summary: A python package for the libsemigroups C++ library.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joseph-edwards
